// Modern Minimal Design Style
// Clean design with subtle shadows, lots of whitespace, and refined typography
// Generated by Vibly

export const theme = {
  // Colors
  colors: {
    primary: '#6366f1',
    secondary: '#8b5cf6',
    accent: '#ec4899',

    background: {
      primary: '#ffffff',
      secondary: '#f8fafc',
      tertiary: '#f1f5f9',
      card: '#ffffff',
      
    },

    text: {
      primary: '#0f172a',
      secondary: '#475569',
      tertiary: '#94a3b8',
      inverse: '#ffffff',
    },

    border: '#e2e8f0',
    success: '#10b981',
    error: '#ef4444',
    warning: '#f59e0b',

    // Compatibility aliases
    label: {
      primary: '#0f172a',
      secondary: '#475569',
      tertiary: '#94a3b8',
    },
    surface: '#f8fafc',

    // iOS System fills
    fill: {
      primary: 'rgba(120, 120, 128, 0.2)',
      secondary: 'rgba(120, 120, 128, 0.16)',
      tertiary: 'rgba(118, 118, 128, 0.12)',
      quaternary: 'rgba(116, 118, 128, 0.08)',
    },

    // Separator colors
    separator: 'rgba(60, 60, 67, 0.29)',
    opaqueSeparator: '#C6C6C8',
  },

  // Gradients
  gradients: {
    primary: {"colors":["#6366f1","#8b5cf6"],"angle":135},
    secondary: {"colors":["#ec4899","#f472b6"],"angle":135},
    
    
  },

  // Shadows
  shadows: {
    none: {},
    sm: {
    "shadowColor": "#000000",
    "shadowOffset": {
        "width": 0,
        "height": 1
    },
    "shadowOpacity": 0.05,
    "shadowRadius": 2,
    "elevation": 1
},
    md: {
    "shadowColor": "#000000",
    "shadowOffset": {
        "width": 0,
        "height": 4
    },
    "shadowOpacity": 0.06,
    "shadowRadius": 6,
    "elevation": 3
},
    lg: {
    "shadowColor": "#000000",
    "shadowOffset": {
        "width": 0,
        "height": 10
    },
    "shadowOpacity": 0.08,
    "shadowRadius": 15,
    "elevation": 6
},
    xl: {
    "shadowColor": "#000000",
    "shadowOffset": {
        "width": 0,
        "height": 20
    },
    "shadowOpacity": 0.1,
    "shadowRadius": 25,
    "elevation": 10
},
    glow: {
    "shadowColor": "#6366f1",
    "shadowOffset": {
        "width": 0,
        "height": 4
    },
    "shadowOpacity": 0.2,
    "shadowRadius": 12,
    "elevation": 6
},
    card: {
    "shadowColor": "#000000",
    "shadowOffset": {
        "width": 0,
        "height": 4
    },
    "shadowOpacity": 0.06,
    "shadowRadius": 12,
    "elevation": 4
},
    button: {
    "shadowColor": "#6366f1",
    "shadowOffset": {
        "width": 0,
        "height": 2
    },
    "shadowOpacity": 0.15,
    "shadowRadius": 4,
    "elevation": 2
},
    elevated: {
    "shadowColor": "#000000",
    "shadowOffset": {
        "width": 0,
        "height": 12
    },
    "shadowOpacity": 0.08,
    "shadowRadius": 24,
    "elevation": 8
},
  },

  // Typography
  typography: {
    fontFamily: 'System',
    headingWeight: '700',
    bodyWeight: '400',

    hero: { fontSize: 40, fontWeight: '700', letterSpacing: -0.5 },
    title1: { fontSize: 32, fontWeight: '700', letterSpacing: -0.5 },
    title2: { fontSize: 24, fontWeight: '700', letterSpacing: -0.5 },
    title3: { fontSize: 20, fontWeight: '600', letterSpacing: 0 },
    headline: { fontSize: 17, fontWeight: '600', letterSpacing: 0 },
    body: { fontSize: 15, fontWeight: '400', letterSpacing: 0 },
    caption: { fontSize: 13, fontWeight: '400', letterSpacing: 0 },
    small: { fontSize: 11, fontWeight: '400', letterSpacing: 0.5 },
  },

  // Spacing
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    xxl: 32,
    xxxl: 48,
    screenPadding: 20,
    cardPadding: 16,
    sectionGap: 24,
  },

  // Border Radius
  borderRadius: {
    none: 0,
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    full: 9999,
    card: 16,
    button: 12,
    input: 12,
  },

  // Component Styles
  components: {
    card: {
      borderRadius: 16,
      borderWidth: 1,
      borderColor: '#f1f5f9',
      style: 'elevated',
      
      
    },
    button: {
      borderRadius: 12,
      borderWidth: 0,
      style: 'filled',
      fontWeight: '600',
      
    },
    input: {
      borderRadius: 12,
      borderWidth: 1,
      style: 'outlined',
    },
  },

  // Style metadata
  meta: {
    name: 'Modern Minimal',
    mode: 'light',
    usesGradients: false,
    usesBlur: false,
    usesBoldBorders: false,
    usesHardShadows: false,
  },
};
